spring.application.name=demo
server.port=8080
 


# Podstawowe dane po\u0142\u0105czenia
spring.datasource.url=jdbc:postgresql://localhost:5432/car_monitoring
spring.datasource.username=postgres
spring.datasource.password=q
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect