spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/car_monitoring
spring.datasource.username=postgres
spring.datasource.password=SCRAM-SHA-256$4096:D9JS81Wemyfr1UEGTXTKmg==$jXuON6K0ylOG1RTu1t8BbATJkdzriCiUx+ySNMYhVmM=:uF3Ibdi/jzBu9Y+5r0ntsp0tP7QUdXvDWhkjlzRhqEw=
spring.jpa.hibernate.ddl-auto=update


